In [1]:
import numpy as np

In [14]:
a = np.zeros((3,3), dtype = np.int64) # By using dtype we can change the data type of our array
a[:] = 2
print(a.dtype, '\n') # Here, this is of float data type
print(a)

int64 

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [15]:
b = np.arange(1,10).reshape(3,3)
print(b.dtype, '\n') # And this is of Int data type
print(b)

int64 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
# c = np.zeros((3,3), dtype = np.int64)
c = np.zeros((3,3))
c.fill(7) # It will fill entire array with value 7

# Also we can easily perform mathematical operations on array.
c += 3
c -= 3
c *= 3
c /= 3
# c /= 3 # This will thorw an error because our existing array if of int type and we are strictly commited to store only int not floating point numbers, that's why it is throwing an error
print(c)

[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [34]:
# Arithmetic Methods
d = np.arange(1,10).reshape(3,3)
arr_sum = d.sum() # It will provide us the sum of entire array
arr_row = d.sum(axis=1) # It will provide us the sum of entire rows of array
print(d, '\n')
print(arr_sum)
arr_row

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

45


array([ 6, 15, 24])

In [37]:
arr_product = a.prod() # This will display the product of entire array
print(arr_product)

512


In [40]:
arr_average = d.mean() # This will display the mean value from the array
print(arr_average)

5.0


In [47]:
arr_max, arr_min = d.max(), d.min() # This will display the maximum and minimum value from the array
print(arr_max, arr_min)

# We can also find out the index of our maximum and minimum values by following method
arr_max_idx, arr_min_idx = d.argmax(), d.argmin()
print(arr_max_idx, arr_min_idx)

# There's an another misterious method related to max and min values in array and this is known as peak to peak method
peak_to_peak = d.ptp() # This is basically equals to 'd,amx() - d.min()', can verify it too
val_diff = d.max() - d.min()
print(peak_to_peak)
print(val_diff)
# Both the values will come out exactly the same

9 1
8 0
8
8


In [51]:
# Flatten arrays (it will create an one-dimensional array, there are several ways to perform this phenomena. So, see below
flat_arr = d.reshape(d.size)
flat_arr1 = d.flatten() # This basically creates an copy of original array
flat_arr2 = d.ravel() # This will create an view of the original array
print(flat_arr)
print(flat_arr1)
print(flat_arr2)
# These are three different ways to perform such task.

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [61]:
# Repeat arrays
arr_repeat = np.repeat(d, 3, axis = 1) # It will repeat all the values of array 'd' along the row
print(arr_repeat, '\n')

# There is also an reverse phenomena for the same, called 'unique'
arr_unique = np.unique(arr_repeat, axis = 1) # This will revert all the changes we've made or repeated values as before
print(arr_unique, '\n')

# We can also have ease access of the diagonals of an entire array, see below.
arr_diagonal = np.diagonal(d) 
arr_d1 = np.diagonal(d, offset = 1) # It will throw diagonal just above the main diagonal
print(arr_diagonal, '\n')
print(arr_d1)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]
 [7 7 7 8 8 8 9 9 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 5 9] 

[2 6]


In [65]:
# Conversion and Storage
my_list = d.tolist()
print(my_list)
print("Type of my_list is: ", type(my_list)) # hence, succesfully converted into list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Type of my_list is:  <class 'list'>


In [68]:
# We can store our array in a file, see below how it can be done
d.tofile('my_array.txt', sep = ',') # It will create an external file and will store array 'd' in it

In [77]:
# Transpose, swapping rows with columns. There are several ways to do so, Let's have a look on it
arr_swapped = np.swapaxes(d, 0, 1)
print(arr_swapped, '\n')

arr_swapped1 = d.transpose(1, 0)
print(arr_swapped1, '\n')

arr_swapped2 = d.T
print(arr_swapped2)

# Hence, transpose of arrays can easily be achieved by this method

[[1 4 7]
 [2 5 8]
 [3 6 9]] 

[[1 4 7]
 [2 5 8]
 [3 6 9]] 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [102]:
# Operations on 2 matrices or arrays
e = np.arange(1,10).reshape(3,3)
print(e, '\n')

f = np.arange(1,10).reshape(3,3)
print(f, '\n')

arr_sum = e + f
print(arr_sum, '\n')

# We can perform any sort of operation 
ops = (e + f - 3*e)/4
print(ops, '\n')

modulo = e % a
print(modulo, '\n')

floor_division = e // a # It will store the remainder in array but as a Integer data type
print(floor_division, '\n')

floor_division1 = np.floor(e/a) # This will also work same as above ops does but this will return as Float data type
print(floor_division1)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 

[[-0.25 -0.5  -0.75]
 [-1.   -1.25 -1.5 ]
 [-1.75 -2.   -2.25]] 

[[1 0 1]
 [0 1 0]
 [1 0 1]] 

[[0 1 1]
 [2 2 3]
 [3 4 4]] 

[[0. 1. 1.]
 [2. 2. 3.]
 [3. 4. 4.]]


In [109]:
# Matrix Multiplication
arr_mult = a * b
print(arr_mult, '\n')

# Above multiplication is multiplication of elements of matrices. So, if we want to perform complete matrics mulitplication we can done it in several ways, see below for more
matrix_multiply = np.matmul(a,b)
print(matrix_multiply, '\n')

matrix_multiply1 = a.dot(b)
print(matrix_multiply1, '\n')

matrix_multiply2 = a @ b
print(matrix_multiply2)

# This is how matrix mulplication can be done

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 

[[24 30 36]
 [24 30 36]
 [24 30 36]] 

[[24 30 36]
 [24 30 36]
 [24 30 36]] 

[[24 30 36]
 [24 30 36]
 [24 30 36]]
