In [3]:
import numpy as np

In [4]:
my_array = np.arange(8) # this is a way to create array via numpy.
# here, '8' will work as a stop point but excluding '8' and by default it'll start from '0'

In [5]:
my_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
print(type(my_array))

<class 'numpy.ndarray'>


In [7]:
# If we want to not to include 0 in previous example and want to start it with 1, then we can change our starting point from 0 to 1
my_array = np.arange(1,8)
my_array

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
# And again what if we want to include only odd digits in our output it is also possible and we can done it by specifying something which is called 'steps'
my_array = np.arange(1,8,2)
my_array

array([1, 3, 5, 7])

In [9]:
# So, here we can say that with np.arange method contains (start, stop, step) and it can be verified from our previous example and one more see below
my_array = np.arange(1,8,0.5) # it will give us whole number in our output
my_array 

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5])

In [10]:
# THERE ARE SEVERAL OTHER WAYTS TO FORM LISTs AND ONE OF THEM WE'VE ALREADY SEEN AND ANOTHER METHOD OF CREATING ARRAY IS CONVERTING ALREADY EXISTED LISTS INTO ARRAY
# Look down and see how it can be done
new_array = np.array([1,2,3])
# List can store vaiour types of data, it simply means lists are really very flexible but the only drawback is that Lists waste large amount of resources, and decreases memory efficiency
# but converting lists into numpy arrays takes required memory or the memory which we specify.
print(type(new_array[0])) # here, we can see that it will takes up '64' bits of memory which is not necessary anymore we can specify memory over here and it will work the same

# So basically we have to convert our decimals to binary to manage it to take less memory
new_array = np.array([1,2,3], dtype = np.int8)
print(type(new_array[0])) # Now here, we'll find out that it will take only '8' bits memory

<class 'numpy.int64'>
<class 'numpy.int8'>


In [57]:
# 2D array
# Creating 2-D arrays are way similar and simple as creating 1-D arrays, See below
tod_array = np.array([[1,2,3], [4,5,6]], dtype = np.int8)
# tod_array # This is one way to create 2-D arrays

In [58]:
# Another way is by using np.arange method
array_2d = np.array((np.arange(1,8,2),np.arange(0,8,2)))
array_2d
print("shape of array is: ", array_2d.shape) # output will be (2, 4) 2 - rows and 4 - columns

shape of array is:  (2, 4)


In [59]:
# We can reshape the array according to our need, it means by swaping number of rows and columns or anything else required to do so
array_2d = array_2d.reshape((4,2))
array_2d

array([[1, 3],
       [5, 7],
       [0, 2],
       [4, 6]])

In [60]:
# another example of it
array_2d = array_2d.reshape((8,)) # It will create a single row for our 2-D array.
array_2d

array([1, 3, 5, 7, 0, 2, 4, 6])

In [61]:
# Way to print empty arrays
emp_arr = np.zeros((2,2)) # generate 0 in whole array
emp_arr = np.ones((3,3)) # Generate 1 in whole array
emp_arr = np.empty((4,5)) # it will generate an array with ranodm numbers
emp_arr

array([[5.09925153e-320, 0.00000000e+000, 6.90038354e-310,
        6.90038355e-310, 6.90038354e-310],
       [6.90038355e-310, 6.90038354e-310, 6.90038443e-310,
        6.90038355e-310, 6.90038354e-310],
       [6.90038355e-310, 6.90038343e-310, 6.90038355e-310,
        6.90038343e-310, 6.90038354e-310],
       [6.90038354e-310, 6.90038361e-310, 6.90038354e-310,
        6.90038343e-310, 6.90038354e-310]])

In [62]:
eye_arr = np.eye(3) # It will create an array with diagnoal elements of value 1
eye_arr = np.eye(3, k = 1) # Diagonal will shift up and If 'k = -1' then diagonal will shift one down
eye_arr

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [63]:
eye_arr[eye_arr == 0] = 2 # all position with value '0' get replaced by 2
eye_arr[eye_arr < 2] = 7 # all values less than 2 get replaced by 7
eye_arr

array([[2., 7., 2.],
       [2., 2., 7.],
       [2., 2., 2.]])

In [64]:
eye_arr[0] = 2 # first row get replace by 3
eye_arr

array([[2., 2., 2.],
       [2., 2., 7.],
       [2., 2., 2.]])

In [65]:
eye_arr[:2] = 4 # first two rows get replacd by 3
eye_arr

array([[4., 4., 4.],
       [4., 4., 4.],
       [2., 2., 2.]])

In [66]:
eye_arr[1:] = 7 # Last two rows will get replaced by 7
eye_arr

array([[4., 4., 4.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [67]:
eye_arr[:, 0] = 5 # first column will get replaced by 5
eye_arr

array([[5., 4., 4.],
       [5., 7., 7.],
       [5., 7., 7.]])

In [68]:
eye_arr[:, -1] = 8 # last column will get replaced by 8
eye_arr

array([[5., 4., 8.],
       [5., 7., 8.],
       [5., 7., 8.]])

In [69]:
# This is how we can furthur customize our array.
eye_arr[:2, :2] = 9
eye_arr

array([[9., 9., 8.],
       [9., 9., 8.],
       [5., 7., 8.]])

In [70]:
# We also can sort the arrays, see below
sorted_arr = np.sort(eye_arr) # This will arrange values in array in a perfect manner (row wise)
sorted_arr

array([[8., 9., 9.],
       [8., 9., 9.],
       [5., 7., 8.]])

In [71]:
sorted_arr = np.sort(eye_arr, axis = 0) # It will sort array column wise
sorted_arr

array([[5., 7., 8.],
       [9., 9., 8.],
       [9., 9., 8.]])

In [73]:
# There are two ways to copy an entire array into another.
my_view = sorted_arr.view()
my_copy = sorted_arr.copy()
print(my_view)
print(my_copy)

[[5. 7. 8.]
 [9. 9. 8.]
 [9. 9. 8.]]
[[5. 7. 8.]
 [9. 9. 8.]
 [9. 9. 8.]]


In [78]:
# Why we need both the ways of copying an entire array, is because view() method actually modifies the original array which then affects the furthur results
my_view[:] = 5
print(my_view, '\n')
print(sorted_arr) # here, you'll find out that original array is also modified that's why we prefer the copy() method to do so

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]] 

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [79]:
# Above scenerio works only in case of values not in case of shape, it means if we'll try to change the shape of array then shape of original array won't be affected